### ISSUE TITLE
Google Wallet instead of google pay

### ISSUE THREAD

**Issue by shahram7** [BigBoot/GW4Remap#10]
Hi Guys 

Google has replaced google pay with google wallet and now my hardware key doesn't work again.

package:com.google.android.apps.walletnfcrel

best regards

**Comment by VNRARA** [comment]
I was hoping this was already fixes with an update.

**Comment by joecksma** [comment]
Hi,
just found out how to fix this until the app is updated.

You need to replace the target app-id of the old Google Pay app: 
com.google.android.apps.walletnfcrel/com.google.commerce.tapandpay.**android.wearable.cardlist.WearPayActivity**

with the new app-id of Google Wallet:
com.google.android.apps.walletnfcrel/com.google.commerce.tapandpay.**wear.cardlist.WalletThemedWearCardListActivity**

**Comment by crookedview** [comment]
Piggybacking on @joecksma's solution - 

You can also connect to the watch via ADB and input the updated app id (press on the app name field, it'll open the keyboard/editor.  remove existing package name):
`adb shell input text "com.google.android.apps.walletnfcrel/com.google.commerce.tapandpay.wear.cardlist.WalletThemedWearCardListActivity"`

**Comment by VNRARA** [comment]
Is there any other activity that opens the app better? It fails to do so since the update and this solution.

**Comment by BigBoot** [comment]
Thanks to @joecksma this is fixed in [v1.0.1](https://github.com/BigBoot/GW4Remap/releases/tag/v1.0.1) as well as [v2.0.0-alpha1](https://github.com/BigBoot/GW4Remap/releases/tag/v2.0.0-alpha1)

**Comment by snijdelwijk** [comment]
> Thanks to @joecksma this is fixed in [v1.0.1](https://github.com/BigBoot/GW4Remap/releases/tag/v1.0.1) as well as [v2.0.0-alpha1](https://github.com/BigBoot/GW4Remap/releases/tag/v2.0.0-alpha1)

The 1.01 does The job for me. Thanks.

The 2.0 alpha doesn't work.
(I tried to replace samsung pay longpress with google wallet on a s21 ultra.)

**Comment by BigBoot** [comment]
Did you follow the setup as described in
https://github.com/BigBoot/GW4Remap/issues/4#issuecomment-1158188672 ?

Am Sa., 23. Juli 2022 um 17:42 Uhr schrieb snijdelwijk <
***@***.***>:

**Comment by snijdelwijk** [comment]
Didn't do those steps

**Comment by BigBoot** [comment]
How did you install the apk?
The instructions basically just are a bunch of adb commands that need to be
executed.

**Comment by VNRARA** [comment]
> > Thanks to @joecksma this is fixed in [v1.0.1](https://github.com/BigBoot/GW4Remap/releases/tag/v1.0.1) as well as [v2.0.0-alpha1](https://github.com/BigBoot/GW4Remap/releases/tag/v2.0.0-alpha1)
> 
> The 1.01 does The job for me. Thanks.
> 
> The 2.0 alpha doesn't work. (I tried to replace samsung pay longpress with google wallet on a s21 ultra.)

Ur dutch? We don't have Samsung Pay yet in the Netherlands...

**Comment by snijdelwijk** [comment]
> How did you install the apk? The instructions basically just are a bunch of adb commands that need to be executed. Message ID: ***@***.***>
> […](#)

I installed the apk from phone to watch with easy fire tools

**Comment by snijdelwijk** [comment]
> > > Thanks to @joecksma this is fixed in [v1.0.1](https://github.com/BigBoot/GW4Remap/releases/tag/v1.0.1) as well as [v2.0.0-alpha1](https://github.com/BigBoot/GW4Remap/releases/tag/v2.0.0-alpha1)
> > 
> > 
> > The 1.01 does The job for me. Thanks.
> > The 2.0 alpha doesn't work. (I tried to replace samsung pay longpress with google wallet on a s21 ultra.)
> 
> Ur dutch? We don't have Samsung Pay yet in the Netherlands...

Ja zeker

**Comment by BigBoot** [comment]
> > How did you install the apk? The instructions basically just are a bunch of adb commands that need to be executed. Message ID: _**@**_.***>
> > […](#)
> 
> I installed the apk from phone to watch with easy fire tools

I don't think you can execute shell commands with Easy Fire Tools.
I've heard it's possible using [Bugjaeger](https://play.google.com/store/apps/details?id=eu.sisik.hackendebug&hl=gsw&gl=US), but I've never used it myself, you basically just need a way to execute shell commands over adb
