### ISSUE TITLE
Use modded APK that replaces Samsung Pay (same package name)

### ISSUE THREAD

**Issue by MicaelJarniac** [BigBoot/GW4Remap#7]
I've had an idea that might be impossible, but I'm no Android dev to be sure, so I decided to share.

Currently, what we have seems to work like so:
- Constantly monitor app launches
- If Samsung Pay, quickly launch Google Pay over it

My idea would be like this:
- Uninstall Samsung Pay
- Install custom APK that has the same package name as Samsung Pay
- Custom APK would be designed to work as just a shortcut to Google Pay
- When button held down, watch will try to open "Samsung Pay"
- That'll make it open the custom APK instead, which will in turn open Google Pay

This would allow us to completely remove Samsung Pay, would remove the need of constantly monitoring app launches, would remove the need for an acessibility service, and would fix the issue of Samsung Pay being open in the background while using Google Pay.

It's a bit less straight-forward, so if it's even possible to do, I don't think it'd be the default method, but more like an extra method for those who want a slightly better experience, at the expense of a couple more ADB commands.

This custom redirecting APK could even be designed to allow the target app to be customizable, so it's not hardcoded to Google Pay.

**Comment by blunden** [comment]
I independently had the same idea and implemented it for use by people in regions where Samsung Pay isn't preinstalled on the watch.

https://github.com/blunden/SPayToGPay

For watches where Samsung Pay is preinstalled, I would expect a signature mismatch when attempting to install it, even if you uninstall the app for user 0 on your watch.

**Comment by BigBoot** [comment]
As @blunden already said, you can't uninstall samsung pay without root, so this will only work for regions without samsung pay, I don't intend to add this functionality to GW4Remap, so I'll close the issue
